apiVersion: apps/v1
kind: Deployment
metadata:
  name: gyant
  namespace: gyant
  labels:
    app: gyant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gyant
  template:
    metadata:
      labels:
        app: gyant
    spec:
      containers:
      - name: gyant
        image: IMAGE
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: gyant-service
  namespace: gyant
spec:
  type: LoadBalancer
  selector:
    app: gyant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: gyant
  namespace: gyant
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gyant
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50