apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: gyant-cluster
  region: eu-west-3
nodeGroups:
  - name: worker-group
    instanceType: t2.micro
    desiredCapacity: 2
    minSize: 2
    maxSize: 3