apiVersion: apps/v1
kind: Deployment
metadata:
  name: gyant
  namespace: gyant
  labels:
    app: gyant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gyant
  template:
    metadata:
      labels:
        app: gyant
    spec:
      containers:
      - name: gyant
        image: 627938768582.dkr.ecr.us-west-1.amazonaws.com/gyant:latest
        ports:
        - containerPort: 3000