apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: gyant
  namespace: gyant
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gyant
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50