apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- hpa.yaml

images:
- name: 627938768582.dkr.ecr.us-west-1.amazonaws.com/gyant
  newTag: latest
- name: gyant
  newName: gyant
  newTag: new